language: node_js

node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

install:
  - npm install
  - npm run build

script:
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  local-dir: public/
  on:
    branch: master
